### ISSUE TITLE
如何区分请求类型get、post.... ?

### ISSUE THREAD

**Issue by Baiyongyu** [MQZHot/DaisyNet#1]
刚刚学习Swift，很多语法还不是很明白，不知道楼主这个框架在发起请求的时候是如何区分请求类型的。

**Comment by MQZHot** [comment]
DaisyNet.request(url, params: params)
request方法包含很多默认参数，具体使用跟Alamofire是一致的

func request(
    _ url: String,
    method: HTTPMethod = .get,
    params: Parameters? = nil,
    encoding: ParameterEncoding = URLEncoding.default,
    headers: HTTPHeaders? = nil)

**Comment by Baiyongyu** [comment]
DaisyNet.request(url, params: params).cache(true).responseCacheAndString { value in
            switch value.result {
            case .success(let string):
                
                if value.isCacheData {
                    self.cacheTextView.text = string
                } else {
                    self.textView.text = string
                }
                
            case .failure(let error):
                print(error)
            }
        }

那你写的这里是怎么判断的

**Comment by MQZHot** [comment]
DaisyNet.request(url, params: params)
DaisyNet.request(url, method: .post, params: params)
method参数省略默认get，修改请求类型的话改变method参数

**Comment by Baiyongyu** [comment]
Thanks
