### ISSUE TITLE
DaisyNet.request请求报错

### ISSUE THREAD

**Issue by xxkrcn** [MQZHot/DaisyNet#13]
DaisyNet.request请求总报DaisyValue<Any>(isCacheData: false, result: SUCCESS: {     error = "Invalid API key!"; }用插件测的接口是通着的，没找到原因

**Comment by xxkrcn** [comment]
DaisyNet.request请求总报DaisyValue<Any>(isCacheData: false, result: SUCCESS: {     error = "Invalid API key!"; }用插件测的接口是通着的，没找到原因

**Comment by BusyBoBo** [comment]
这个error是你后端报错的吧

**Comment by xxkrcn** [comment]
嗯，是的，可能是我理解错了，我把token放在dynamicParams里了，就报这个错。后来我把token等放在headers里就好了，请求成功了
