### ISSUE TITLE
params里面参数的顺序会变化，导致缓存的key不一致

### ISSUE THREAD

**Issue by ZSMHup** [MQZHot/DaisyNet#19]
比如demo里面的params
let params = ["keyword" : "", "npc" : "0", "opc" : "20", "type" : "热门视频", "uid" : "2321"]
第一次启动的时候打印 params = ["uid": "2321", "opc": "20", "type": "热门视频", "keyword": "", "npc": "0"]
杀死程序重新启动打印 params = ["uid": "2321", "npc": "0", "keyword": "", "opc": "20", "type": "热门视频"]
所以每次缓存的key都不一样

**Comment by MQZHot** [comment]
参数进行了一下排序，可以看一下`CacheKey.swift`中的代码
