### ISSUE TITLE
能麻烦适配一下Swift5吗？

### ISSUE THREAD

**Issue by helloMrTom** [MQZHot/DaisyNet#22]
刚刚用pod 'Alamofire', '~> 5.0.0-rc.2'，和cache的5.2.0配合使用，一堆报错，还有就是cache包报了一个Command CompileSwift failed with a nonzero exit code，不知道怎么解决了

**Comment by huxq-coder** [comment]
同问，不维护了吗

**Comment by alucardulad** [comment]
我联系了作者做了简单的升级维护。马上可以用了。已经支持swift5了

**Comment by alucardulad** [comment]
已经可以了。去pod更新下。
