### ISSUE TITLE
Option to use a custom file name for downloaded file.

### ISSUE THREAD

**Issue by talk2cerlin** [MQZHot/DaisyNet#5]
How do i change the file name in which the downloaded file will be written?

as of now i can see you are using `response.suggestedFilename ?? ""` for name. It would be great if that can be overridden manually

**Comment by MQZHot** [comment]
Thanks for attention

There is no open api to modify the file name now, You can expose the fileName by modifying the method below
```swift
private func downloadDestination(fileName: String) -> DownloadRequest.DownloadFileDestination
```
